query GetTasks($userId: ID!) {
  getTasks(userId: $userId) {
    uuid
    title
    description
    repetition
    type
    status
    priority
    projectId
    startDate
    dueDate
    creator {
      uuid
      username
      email
      displayName
      avatarUrl
      createdAt
      updatedAt
    }
    tags {
      uuid
      name
      color
      ownershipType
      workspaceId
      label {
        uuid
        name
        description
      }
    }
    taskCompletionLogs {
      taskCompletionId
      taskId
      userId
      date
      completedAt
    }
    assignees {
      userId
      user {
        uuid
        username
        displayName
        email
        avatarUrl
      }
    }
  }
}

query PersonalTasks($userId: UUID!) {
  personalTasks(userId: $userId) {
    uuid
    title
    description
    repetition
    type
    status
    priority
    projectId
    startDate
    dueDate
    creator {
      uuid
      username
      email
      displayName
      avatarUrl
      createdAt
      updatedAt
    }
    tags {
      uuid
      name
      color
      ownershipType
      workspaceId
      createdBy
      createdAt
      updatedAt
      creator {
        uuid
        username
        email
        displayName
        avatarUrl
        createdAt
        updatedAt
      }
      label {
        uuid
        name
        description
      }
    }
    taskCompletionLogs {
      taskCompletionId
      taskId
      userId
      date
      completedAt
      status
      user {
        uuid
        username
        email
        displayName
        avatarUrl
        createdAt
        updatedAt
      }
    }
    assignees {
      taskId
      userId
      user {
        uuid
        username
        displayName
        email
        avatarUrl
        createdAt
        updatedAt
      }
    }
  }
}

query PersonalTasksByDateRange($userId: UUID!, $from: LocalDate!, $to: LocalDate!) {
  personalTasksByDateRange(userId: $userId, from: $from, to: $to) {
    uuid
    title
    description
    repetition
    type
    status
    priority
    projectId
    startDate
    dueDate
    creator {
      uuid
      username
      email
      displayName
      avatarUrl
      createdAt
      updatedAt
    }
    tags {
      uuid
      name
      color
      ownershipType
      workspaceId
      createdBy
      createdAt
      updatedAt
      creator {
        uuid
        username
        email
        displayName
        avatarUrl
        createdAt
        updatedAt
      }
      label {
        uuid
        name
        description
      }
    }
    taskCompletionLogs {
      taskCompletionId
      taskId
      userId
      date
      completedAt
      status
      user {
        uuid
        username
        email
        displayName
        avatarUrl
        createdAt
        updatedAt
      }
    }
    assignees {
      taskId
      userId
      user {
        uuid
        username
        displayName
        email
        avatarUrl
        createdAt
        updatedAt
      }
    }
  }
}

query GetTaskCompletionLogs($taskId: ID!) {
  getTaskCompletionLogs(taskId: $taskId) {
    taskCompletionId
    taskId
    userId
    date
    completedAt
  }
}

mutation CreateTask($input: CreateTaskInput!) {
  createTask(input: $input) {
    uuid
    title
    description
    repetition
    type
    status
    priority
    projectId
    startDate
    dueDate
    creator {
      uuid
      username
      email
      displayName
      avatarUrl
      createdAt
      updatedAt
    }
    assignees {
      userId
      user {
        uuid
        username
        displayName
        email
        avatarUrl
      }
    }
  }
}

mutation UpdateTask($input: UpdateTaskInput!) {
  updateTask(input: $input) {
    uuid
    title
    description
    repetition
    type
    status
    priority
    projectId
    startDate
    dueDate
    assignees {
      userId
      user {
        uuid
        username
        displayName
        email
        avatarUrl
      }
    }
  }
}

mutation DeleteTask($uuid: ID!) {
  deleteTask(uuid: $uuid) {
    uuid
  }
}

mutation MarkTaskDone($input: MarkTaskDoneInput!) {
  markTaskDone(input: $input) {
    taskCompletionId
    taskId
    userId
    date
    completedAt
  }
}

mutation MarkTaskWontDo($input: MarkTaskDoneInput!) {
  markTaskWontDo(input: $input) {
    taskCompletionId
    taskId
    userId
    date
    completedAt
  }
}