# PostgreSQL config for production
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://postgresql:postgresql@localhost:5432/devdb}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Do not update schema automatically in prod
#spring.jpa.hibernate.ddl-auto=validate
