spring.application.name=backend

# JWT Configuration
jwt.secret=9a4f4c354567f16c52643a2f4a526b5a452f465a4435426c4a31785535313936
jwt.expiration=86400000
server.port=8080
spring.profiles.active=dev

# Enable GraphQL UI for testing
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.websocket.path=/graphql
app.base-url=http://localhost:8080

spring.jpa.hibernate.ddl-auto=update
