# We will use Testcontainers for Dev database context
#spring.datasource.url=jdbc:postgresql://localhost:5432/devdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://pg-278ee8b8-social-listener-tool.h.aivencloud.com:14451/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_fl7zp0LgQWvcgFOOG4y

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.graphql.websocket.path=/graphql


logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.graphql=TRACE

cloudinary.cloud-name=de5l5byyn
cloudinary.api-key=572949972461723
cloudinary.api-secret=lAGGxiW9auX4FZj9ImqU8RWfpbc